@import header

name: 'build-test'

on: [pull_request, push]

# secrets:
#  * GOOGLE_CREDENTIALS - base64 encoded google service account credentials, must be a single line with no whitespace
#  * RESULTS_SHEET_ID - google sheets id of sheet to upload results to
env:
  SECRET_GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  SECRET_RESULTS_SHEET_ID: ${{ secrets.RESULTS_SHEET_ID }}
jobs:
  build_and_test:
    name: '${{ matrix.os }}: build and test (install mdns: ${{ matrix.install_mdns }}, use conan: ${{ matrix.use_conan }}, force cpprest asio: ${{ matrix.force_cpprest_asio }})'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        install_mdns: [false]
        use_conan: [true]
        force_cpprest_asio: [false]
        include:
          - install_mdns: true
            use_conan: true
            force_cpprest_asio: false
            os: ubuntu-18.04
          - install_mdns: true
            use_conan: true
            force_cpprest_asio: false
            os: ubuntu-20.04
          - install_mdns: false
            use_conan: true
            force_cpprest_asio: true
            os: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: set environment variables
      shell: bash
      run: |
        if [[ "${{ runner.os }}"  == "Linux" ]]; then
          if [[ "${{ matrix.install_mdns }}" == "true" ]]; then
            echo "BUILD_NAME=${{ matrix.os }}_mdns" >> $GITHUB_ENV
          else
            echo "BUILD_NAME=${{ matrix.os }}_avahi" >> $GITHUB_ENV
          fi
        elif [[ "${{ matrix.force_cpprest_asio }}" == "true" ]]; then
          echo "BUILD_NAME=${{ matrix.os }}_asio" >> $GITHUB_ENV
        else
          echo "BUILD_NAME=${{ matrix.os }}" >> $GITHUB_ENV
        fi
        GITHUB_COMMIT=`echo "${{ github.sha }}" | cut -c1-7`
        echo "GITHUB_COMMIT=$GITHUB_COMMIT" >> $GITHUB_ENV
        echo "GITHUB_WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV
        echo "RUNNER_WORKSPACE=${{ runner.workspace }}" >> $GITHUB_ENV

    - name: install python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install pip
      run: |
        python -m pip install --upgrade pip

    @import build-and-test

  build_and_test_ubuntu_14:
    name: 'ubuntu-14.04: build and test (install mdns: ${{ matrix.install_mdns }}, use conan: ${{ matrix.use_conan }})'
    runs-on: ubuntu-latest
    container:
      image: ubuntu:14.04
    strategy:
      fail-fast: false
      matrix:
        install_mdns: [true]
        use_conan: [false]

    steps:
    - uses: actions/checkout@v2

    - name: set environment variables
      run: |
        echo "BUILD_NAME=ubuntu-14.04_mdns" >> $GITHUB_ENV
        GITHUB_COMMIT=`echo "${{ github.sha }}" | cut -c1-7`
        echo "GITHUB_COMMIT=$GITHUB_COMMIT" >> $GITHUB_ENV
        # github.workspace points to the host path not the docker path, the home directory defaults to the workspace directory
        echo "GITHUB_WORKSPACE=`pwd`" >> $GITHUB_ENV
        cd ..
        echo "RUNNER_WORKSPACE=`pwd`" >> $GITHUB_ENV

    - name: install build tools
      run: |
        apt-get update -q
        apt-get install -y software-properties-common
        add-apt-repository ppa:deadsnakes/ppa -y
        apt-get --allow-unauthenticated update -q
        apt-get --allow-unauthenticated install -y curl g++ git make patch python3.6 python3.6-gdbm bsdmainutils dnsutils unzip
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 3
        ln -s /usr/bin/python3.6 /usr/bin/python
        curl -sS https://bootstrap.pypa.io/get-pip.py | python
        curl -sS https://nodejs.org/dist/v12.16.2/node-v12.16.2-linux-x64.tar.xz | tar -xJ
        echo "`pwd`/node-v12.16.2-linux-x64/bin" >> $GITHUB_PATH

    @import build-and-test

  make_badges:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: [build_and_test, build_and_test_ubuntu_14]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set environment variables
      shell: bash
      run: |
        GITHUB_COMMIT=`echo "${{ github.sha }}" | cut -c1-7`
        echo "GITHUB_COMMIT=$GITHUB_COMMIT" >> $GITHUB_ENV
        echo "GITHUB_WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV
        echo "RUNNER_WORKSPACE=${{ runner.workspace }}" >> $GITHUB_ENV

    - uses: actions/download-artifact@v2.0
      with:
        path: ${{ runner.workspace }}/artifacts

    - name: make badges
      run: |
        # combine badges from all builds, exclude macos-latest
        ${{ github.workspace }}/Sandbox/make_badges.sh ${{ github.workspace }} ${{ runner.workspace }}/artifacts macos-latest

        # force push to github onto an orphan 'badges' branch
        cd ${{ github.workspace }}
        git checkout --orphan badges-${{ env.GITHUB_COMMIT }}
        git rm -rfq --ignore-unmatch .
        git add *.svg
        git remote set-url --push `git remote` https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git config --global user.name 'test-results-uploader'
        git config --global user.email 'test-results-uploader@nmos-cpp.iam.gserviceaccount.com'
        git commit -qm "Badges for README at ${{ env.GITHUB_COMMIT }}"
        git push -f `git remote` badges-${{ env.GITHUB_COMMIT }}:badges
